// Values originate in project documents: never render them as active HTML.
export function knowledgeView(data, esc) {
  const memory = data || {};
  const labels = { proposed: 'À confirmer', accepted: 'Relu et accepté', confirmed: 'Confirmé', superseded: 'Remplacé',
    unknown: 'Non vérifié', verified: 'Sources vérifiées', stale: 'À relire', validated: 'Validé localement',
    deferred: 'Différé', discovery: 'Découverte', decision: 'Décision', question: 'Question',
    implementation: 'Réalisation', deployment: 'Déploiement', draft: 'Brouillon', reference: 'Référence', historical: 'Historique' };
  const label = value => labels[value] || value || 'Non renseigné';
  const refs = rows => (rows || []).map(r => `<code class="path">${esc(r.path)}</code>`).join('');
  const decisions = memory.decisions || [], rows = memory.contributions || [], documents = memory.documents || [], receipts = memory.receipts || [];
  const current = rows.filter(r => r.current);
  const alerts = [...(memory.warnings || []), ...rows.filter(r => r.warning).map(r => `${r.id} : ${r.warning}`),
    ...documents.filter(r => r.warning).map(r => `${r.id} : ${r.warning}`)];
  const cards = items => items.join('') || '<p class="muted">Aucun élément enregistré.</p>';
  const openQuestions = (memory.questions || []).filter(q => q.status === 'open');
  const untouched = !current.length && !decisions.length && !documents.length && !receipts.length && !openQuestions.length;
  if (untouched) return `<div class="page knowledge-page"><div class="section-title"><div><h2>Mémoire partagée</h2><p class="muted">${esc(memory.release ? `Release ${memory.release}` : 'Toutes les releases du projet')}</p></div></div>
    ${alerts.length ? `<section class="knowledge-alert" role="status"><h3>À relire avant de poursuivre</h3><ul>${alerts.map(a => `<li>${esc(a)}</li>`).join('')}</ul></section>` : ''}
    <p class="note">La mémoire structurée n’est pas encore alimentée. Les agents y publieront découvertes, décisions et passations au fil du travail ; les documents PROJECT et JOURNAL restent disponibles dans Projet → Fichiers.</p>
    ${memory.source_index ? `<h3>Index du code</h3><div class="info-card"><h4>Odoo ${esc(memory.source_index.series)} · sources vérifiées</h4>${memory.source_index.layers.map(l => `<p><strong>${esc(l.layer)}</strong> · ${esc(l.modules.join(', '))} · ${esc(l.symbols)} symboles</p>`).join('')}</div>` : ''}
    <p class="muted">${esc(memory.limitation || 'Installez la version actuelle d’Odoo Crew pour vérifier ces informations.')} Consultation seule ; l’orchestrateur publie les changements.</p></div>`;
  return `<div class="page knowledge-page"><div class="section-title"><div><h2>Mémoire partagée</h2><p class="muted">${esc(memory.release ? `Release ${memory.release}` : 'Toutes les releases du projet')} · alimentée pendant le travail</p></div></div>
    ${alerts.length ? `<section class="knowledge-alert" role="status"><h3>À relire avant de poursuivre</h3><ul>${alerts.map(a => `<li>${esc(a)}</li>`).join('')}</ul></section>` : ''}
    <div class="knowledge-summary"><span><strong>${decisions.filter(d => d.status === 'confirmed').length}</strong> décisions confirmées</span><span><strong>${current.length}</strong> contributions courantes</span><span><strong>${receipts.filter(r => r.state === 'validated').length}</strong> passations validées</span><span><strong>${documents.length}</strong> pièces cataloguées</span></div>
    <h3>Au fil de la release</h3><div class="knowledge-list">${cards(current.map(r => `<article class="info-card"><div class="card-title"><h4>${esc(r.id)} · ${esc(label(r.kind))}</h4><span class="knowledge-state">${esc(label(r.state))} · ${esc(label(r.freshness))}</span></div><p>${esc(r.statement)}</p><p class="muted">${esc(r.release)}${r.task ? ` · ${esc(r.task)}` : ''}${r.author ? ` · ${esc(r.author)}` : ''}</p>${refs(r.sources)}${r.scope?.length ? `<p>Périmètre : ${esc(r.scope.join(', '))}</p>` : ''}</article>`))}</div>
    <h3>Acquis des tâches</h3><div class="knowledge-list">${cards(receipts.map(r => `<details class="info-card"><summary>${esc(r.task)} · ${esc(label(r.state))} · ${esc(r.release)}</summary><pre class="knowledge-text">${esc(r.text || r.warning)}</pre>${refs([r.source])}</details>`))}</div>
    ${openQuestions.length ? `<h3>Questions ouvertes du projet</h3><div class="knowledge-list">${openQuestions.map(q => `<article class="info-card"><h4>${esc(q.id)}</h4><p>${esc(q.question)}</p>${refs([q.source])}</article>`).join('')}</div>` : ''}
    <h3>Décisions du projet</h3><div class="knowledge-list">${cards(decisions.filter(d => d.status !== 'superseded').map(d => `<article class="info-card"><h4>${esc(d.id)} · ${esc(label(d.status))}</h4><p>${esc(d.statement)}</p>${d.exceptions?.length ? `<p><strong>Exceptions :</strong> ${esc(d.exceptions.join('; '))}</p>` : ''}${d.scope?.length ? `<p>Périmètre : ${esc(d.scope.join(', '))}</p>` : ''}${refs(d.sources)}</article>`))}</div>
    <h3>Documents et repères</h3><div class="knowledge-list">${cards(documents.map(d => `<details class="info-card"><summary>${esc(d.id)} · ${esc(d.version)} · ${esc(label(d.status))} · ${esc(label(d.freshness))}</summary>${refs([d.original])}<p class="muted">${esc(d.limitation || 'Extraction textuelle')}</p>${d.chunks?.length ? d.chunks.map(c => `<p><strong>${esc(c.location)}</strong></p><pre class="knowledge-text">${esc(c.text)}</pre>`).join('') : '<p>Consulter l’original ; aucune extraction vérifiée disponible.</p>'}</details>`))}</div>
    <h3>Index du code</h3>${memory.source_index ? `<div class="info-card"><h4>Odoo ${esc(memory.source_index.series)} · sources vérifiées</h4>${memory.source_index.layers.map(l => `<p><strong>${esc(l.layer)}</strong> · ${esc(l.modules.join(', '))} · ${esc(l.symbols)} symboles<br><code>${esc(l.revision || 'Révision Git non disponible')}</code></p>`).join('')}<p class="muted">${esc(memory.source_index.limitation)}</p></div>` : '<p class="muted">Aucun index de code vérifié. La bibliothèque et les versions restent consultables dans Projet → Sources.</p>'}
    ${rows.some(r => !r.current) || decisions.some(d => d.status === 'superseded') ? `<details class="info-card"><summary>Historique des remplacements</summary>${rows.filter(r => !r.current).map(r => `<p>${esc(r.id)} · ${esc(r.release)} · remplacé</p>`).join('')}${decisions.filter(d => d.status === 'superseded').map(d => `<p>${esc(d.id)} → ${esc(d.superseded_by)}</p>`).join('')}</details>` : ''}
    <p class="muted">${esc(memory.limitation || 'Installez la version actuelle d’Odoo Crew pour vérifier ces informations.')} Consultation seule ; l’orchestrateur publie les changements.</p></div>`;
}
